name: Action Test On Commit
on: [push]
jobs:
  testBuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install JDK 16
        uses: actions/setup-java@v3
        with:
          java-version: 16
          distribution: adopt
      - name: MVN Verify Application
        run: mvn -s maven-settings.cml --batch-mode --update-snapshots verify
        env: {vars}
